---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 733355682599174144-pWNjNvuTwsCBMmsoAmA2FE2YrZPuV77
:access_token_secret: XNRvPU5Jef9OVP7P5WrnCVfZ3vALDEUF6hgdCvycsuCMd
